'CREATE TABLE `Flights` (
  `Flight_Date` date NOT NULL,
  `Airline_ID` int(11) DEFAULT NULL,
  `Flight_Num` int(11) NOT NULL,
  `Depart_Time` time DEFAULT NULL,
  `Depart_Airport` varchar(5) DEFAULT NULL,
  `Depart_Airport_City_ID` int(11) DEFAULT NULL,
  `Depart_Airport_State` varchar(5) DEFAULT NULL,
  `Arrival_Time` time DEFAULT NULL,
  `Arrival_Airport` varchar(5) DEFAULT NULL,
  `Arrival_Airport_City_ID` int(11) DEFAULT NULL,
  `Arrival_Airport_State` varchar(5) DEFAULT NULL,
  `Distance` int(11) DEFAULT NULL,
  PRIMARY KEY (`Flight_Num`,`Flight_Date`),
  KEY `Depart_Airport` (`Depart_Airport`),
  KEY `Arrival_Airport` (`Arrival_Airport`),
  KEY `Depart_Airport_City_ID` (`Depart_Airport_City_ID`),
  KEY `Arrival_Airport_City_ID` (`Arrival_Airport_City_ID`),
  KEY `Depart_Airport_State` (`Depart_Airport_State`),
  KEY `Arrival_Airport_State` (`Arrival_Airport_State`),
  KEY `Airline_ID` (`Airline_ID`),
  CONSTRAINT `Flights_ibfk_1` FOREIGN KEY (`Depart_Airport`) REFERENCES `Airports` (`Airport_Code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_2` FOREIGN KEY (`Arrival_Airport`) REFERENCES `Airports` (`Airport_Code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_3` FOREIGN KEY (`Depart_Airport_City_ID`) REFERENCES `City_of_Airports` (`City_Market_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_4` FOREIGN KEY (`Arrival_Airport_City_ID`) REFERENCES `City_of_Airports` (`City_Market_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_5` FOREIGN KEY (`Depart_Airport_State`) REFERENCES `State_of_Airports` (`State_Code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_6` FOREIGN KEY (`Arrival_Airport_State`) REFERENCES `State_of_Airports` (`State_Code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Flights_ibfk_7` FOREIGN KEY (`Airline_ID`) REFERENCES `Airlines` (`Airline_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1'